[workspace]
resolver = "2"
members = [
    "zhang-core",
    "zhang-ast",
    "zhang-server",
    "zhang-cli",
    "extensions/*",
    "bindings/python",
    "bindings/wasm",
]

[profile.dev]
split-debuginfo = "unpacked"
