name: Snapshot Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: frontend install
        run: yarn install
        working-directory: ./frontend
      
      - name: frontend build
        run: yarn run build
        working-directory: ./frontend

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      
      - name: build musl target release
        run: docker run -v $PWD:/volume -v "/home/runner/.cargo/registry":/root/.cargo/registry clux/muslrust:stable cargo build --release

      - name: Docker build
        run: docker build --tag ghcr.io/kilerd/zhang:snapshot .
      
      - name: docker push image
        run: docker push ghcr.io/kilerd/zhang:snapshot