name: Snapshot Build

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  pages: write

env:
  # Name of module and id separated by a slash
  INSTANCE: Writerside/zhang
  # Replace XX with the ID of the instance in capital letters
  ARTIFACT: webHelpZHANG2-all.zip
  # Docker image version
  DOCKER_VERSION: 2.1.1479-p3869
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: frontend install
        run: yarn install
        working-directory: ./frontend

      - name: frontend build
        run: yarn run build
        working-directory: ./frontend

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            kilerd/zhang:snapshot
      - name: Echo git commit hash to file
        run: |
          mkdir example-deployment
          echo "${GITHUB_SHA}" > ./example-deployment/git_sha
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'example-deployment'
          destination-github-username: 'zhang-accounting'
          destination-repository-name: 'zhang-example'
          target-directory: 'example-deployment'
          user-email: blove694@gmail.com
          target-branch: main
