name: Snapshot Build

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Snapshot build on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [macos, ubuntu, windows]
        include:
          - platform: macos
            target: x86_64-apple-darwin
            os: macos-latest
            bin: zhang

          - platform: ubuntu
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            bin: zhang
          
          - platform: windows
            target: x86_64-pc-windows-msvc
            os: windows-latest
            bin: zhang.exe
    steps:
      - uses: actions/checkout@v1

      - name: frontend install
        run: yarn install
        working-directory: ./frontend
      
      - name: frontend build
        run: yarn run build
        working-directory: ./frontend

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run code build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Prepare assets
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          strip ${{ matrix.bin }}
          tar czvf zhang-${{ matrix.platform }}.tar.gz ${{ matrix.bin }}
      
      - name: Release assets
        uses: softprops/action-gh-release@v1
        with:
          name: snapshot-build-${{ github.run_id }}
          files: target/${{ matrix.target }}/release/zhang-${{ matrix.platform }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}